#!/bin/bash

###############################################################################
# ansi color constants for bash
# Copyright 2016 C. Byerley

# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at:

#	http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
###############################################################################

###############################################################################
# Usage
# This file is to be 'sourced' into your main bash script.
# You use the color `tags` like HTML tags around your echo outputs.

# Example:
# #!/bin/bash
# . colorsplus
# echo -e "A Firetruck is ${CRED}Red${CEND}"

# NOTE: You much use the `-e` flag when using `echo` for tags to render properly.

###############################################################################
# The Reset Constant `$FIN`
# This `tag` can be used to close all the opening tag types.

#Examples:
# echo -e "${BGRN}This is default text on a green background${FIN}"
# echo -e "Please no ${FBLK}${CRED}Red Blinking${FIN}"

# $FIN is basically a clearing `tag` for any previous styling, and is
# Commonly used at the end of a styled string

# For more control, and `nesting` styles, use the designated "end" tag
#  for each tag type show below.

# NOTE: A set style continues until a close tag is found. By using $FIN you can leave off
# closing tags for formating and color treatment, for example:

# echo -e "${FBLD}${FBLK}${CCYN}This is bold blinking cyan text..yay!${FIN}'"

# In the example above all the opening tags are closed with a single $FIN.

################################################################################
FIN='\033[0m' # 'The End' in French
################################################################################
# Format Start Tags
FBLD='\033[1m' 	 #Bold
FDIM='\033[2m' 	 #Dim
FUL='\033[4m'      #Underline
FBLK='\033[5m'   #Blink
FREV='\033[7m'   #Invert
FHIDE='\033[8m' #Hide

################################################################################
# Format End Tags
FEBLD='\033[21m'   # Remove Bold
FEDIM='\033[22m'   # Remove Dim
FEUL='\033[24m'      # Remove Underline
FEBLK='\033[25m'    # Remove Blink
FEREV='\033[27m'    # Remove Invert
FEHIDE='\033[28m'  # Remove Hide

################################################################################
# End All Format Tag
# This tag reverts the styling to the default set in the terminal.
FEND=$FIN

################################################################################
# Color Contants
################################################################################

################################################################################
# Text Color Default
# The default flag reverts the output to the original default style
# as configured in the users terminal program settings.
# NOTE: $CEND is an alias of this command.
CDEF='\033[39m' #Reverts Background Color to default.

################################################################################
 # Color Constants (base ansi 8)
CBLK='\033[30m'
CRED='\033[31m'
CGRN='\033[32m'
CYEL='\033[33m'
CBLU='\033[34m'
CMAG='\033[35m'
CCYN='\033[36m'
CGRY='\033[37m'
# Color Constants (extended 16)
CDGRY='\033[90m'
CLRED='\033[91m'
CLGRN='\033[92m'
CLYEL='\033[93m'
CLBLU='\033[94m'
CLMAG='\033[95m'
CLCYN='\033[96m'
CWHT='\033[97m'

################################################################################
# End All Color Tag
# This tag reverts the styling to the default set in the terminal.
CEND=$CDEF

################################################################################
# Background Color Constants
################################################################################

################################################################################
# Background Color Default
# The default flag reverts the output to the original default style
# as configured in the users terminal program settings.
# NOTE: $BEND is an alias of this tag.
BDEF='\033[49m' #Reverts Background Color to default.

################################################################################
# Background Color Constants
BBLK='\033[40m' #Black Background
BRED='\033[41m' #Red Background
BGRN='\033[42m' #Green Background
BYEL='\033[43m' #Yellow Background
BBLU='\033[44m' #Blue Background
BMAG='\033[45m' #Magenta Background
BCYN='\033[46m' #Cyan Background
BGRY='\033[47m' #Gray (Lt. Gray) Background
BDGRY='\033[100m' #Dark Gray Background
BLRED='\033[101m' #Light Red Background
BLGRN='\033[102m' #Light Green Background
BLYEL='\033[103m' #Light Yellow Background
BLBLU='\033[104m' #Light Blue Background
BLMAG='\033[105m' #Light Magenta Background
BLCYN='\033[106m' #Light Cyan Background
BGWHT='\033[107m' #White Background

################################################################################
# End All Background Color Tag
# This tag reverts the styling to the default set in the terminal.
BEND=$BDEF

